#!/bin/bash
set -eux

. "$(dirname "$(readlink -f "$0")")"/functions.sh

APT_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-apt-2.1.1.tar.gz"
CONCAT_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-concat-1.2.4.tar.gz"
STDLIB_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-stdlib-4.7.0.tar.gz"
INIFILE_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-inifile-1.4.1.tar.gz"
GRAFANA_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/bfraser-grafana-2.5.0.tar.gz"
MYSQL_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-mysql-3.6.2.tar.gz"
FIREWALL_TARBALL_URL="https://forgeapi.puppetlabs.com/v3/files/puppetlabs-firewall-1.7.2.tar.gz"

download_package https://dl.influxdata.com/influxdb/releases/influxdb_1.1.1_amd64.deb
download_package https://grafanarel.s3.amazonaws.com/builds/grafana_4.1.1-1484211277_amd64.deb
download_package http://mirrors.kernel.org/ubuntu/pool/main/s/systemd-shim/systemd-shim_6-2bzr1_amd64.deb

# Download Puppet modules
download_puppet_module "grafana" "$GRAFANA_TARBALL_URL"
download_puppet_module "apt" "$APT_TARBALL_URL"
download_puppet_module "concat" "$CONCAT_TARBALL_URL"
download_puppet_module "stdlib" "$STDLIB_TARBALL_URL"
download_puppet_module "inifile" "$INIFILE_TARBALL_URL"
download_puppet_module "mysql" "${MYSQL_TARBALL_URL}"
download_puppet_module "firewall" "$FIREWALL_TARBALL_URL"
